"""initial_schema

Revision ID: 942a3b56ae5b
Revises: 
Create Date: 2026-06-10 19:42:57.075086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '942a3b56ae5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_queries_ip_hash'), 'guest_queries', ['ip_hash'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('final_output', sa.Text(), nullable=True),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('token_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('trace_url', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('rating', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_runs')
    op.drop_index(op.f('ix_guest_queries_ip_hash'), table_name='guest_queries')
    op.drop_table('guest_queries')
    # ### end Alembic commands ###
